# Links all files in docs to the README for Jekyll

name: Link

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd docs
          sed '/<hr>/q' README.md
          ls -1 >> README.md
          sed -i '/README.md/d' README.md
          sed -i '/_config.yml/d' README.md
          sed -i '/CNAME/d' README.md
          rm ../README.md
          ln README.md ../
          git config --global user.name 'Runner'
          git config --global user.email 'runner@users.noreply.github.com'
          git commit -am "Automatically link emoji"
          git push || echo "No emoji to update"
